comment:
  layout: header, changes, diff
coverage:
  ignore:
    - tests/*
    - dgemm_tests/*
    - setup.py
    - project/diis.py
    - project/mp2new.py
    - project/scf_response.py
  status:
    patch: false
