# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false
dist: precise

matrix:
  - python: 3.5

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n sss python=3.5 psi4 scipy lawrap -c psi4/label/dev -c psi4
#  - conda create -n sss python=3.5 psi4 pytest pytest-cov numpy lawrap cmake scipy numexp -c psi4/label/dev -c psi4
  - source activate sss
  - conda install cmake
  - conda list
#  - conda cmake
  - pip install codecov

before_script:
  - python -V
  - cd project
  - cmake #../
  - make
  - cd ../

script:
  - pip install -e .
  - py.test -v --cov=./

after_success:
  - codecov

notifications:
  email: false
